language: node_js
node_js:
  - "stable"
env:
  global:
  - CXX=g++-4.8 
  - TEST_PORT=3030 
  - TEST_HOST=http://localhost:3030 
  - TEST_SSL=https://localhost:3030 
  - APP_SECRET=fubar
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run test-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)