language: node_js
node_js:
  - "stable"
before_script:
  - "export TEST_PORT=3030"
  - "export TEST_HOST=http://localhost:3030"
  - "export APP_SECRET=fubar"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run test-coverage
after_success:
  - bash <(curl -s https://codecov.io/bash)